databases:
  - name: cadence
    databaseName: cadence
    user: cadence

services:
  - type: web
    name: cadence
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn cadence.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cadence
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4