# Generated by Django 4.1.1 on 2022-09-15 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='bank/static/avatar/avatar.png', upload_to='bank/static/avatar'),
        ),
    ]
