# Generated by Django 4.1.1 on 2022-09-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_customer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='static/avatar/avatar.png', upload_to='static/avatar'),
        ),
    ]
