# Generated by Django 4.1.1 on 2022-09-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
