# Generated by Django 4.1.1 on 2022-09-17 19:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_customer_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
