# Generated by Django 4.1.1 on 2022-09-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_alter_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='block_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='suspend_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
