# Generated by Django 4.1.1 on 2022-10-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_account_block_account_account_suspend_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CUSTOMER_ID',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_confirmed',
        ),
        migrations.RemoveField(
            model_name='posttransaction',
            name='error_message',
        ),
    ]
