# Generated by Django 4.1.1 on 2022-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_posttransaction_top_up_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttransaction',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
