# Generated by Django 4.1.1 on 2022-10-09 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_posttransaction_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttransaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='posttransaction',
            name='top_up_type',
        ),
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posttransaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CreateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('top_up_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=300, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.account')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
