# Generated by Django 4.1.1 on 2022-10-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_remove_posttransaction_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createhistory',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
