# Generated by Django 4.1.1 on 2022-11-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0020_account_block_account_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='block_account_message',
            field=models.TextField(default='This account has been blocked Kindly contact the administrator to learn more. Or, enter a valid username and password.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='suspend_account_message',
            field=models.TextField(default='This account has been suspended Kindly contact the administrator to learn more. Or, enter a valid username and password.'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
