# Generated by Django 4.1.1 on 2022-12-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_alter_account_block_account_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, default='SkyHigh Premium', max_length=255, null=True),
        ),
    ]
