# Generated by Django 4.1.1 on 2022-12-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_alter_payment_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttransaction',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
