# Generated by Django 4.1.1 on 2022-12-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0023_alter_posttransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
