# Generated by Django 4.1.1 on 2023-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_payment_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('Dollar', '$'), ('Pounds', '£'), ('Euro', '€'), ('Korean Won', '₩'), ('Indian Rupees', '₹'), ('Chinese Yuan', '¥')], default='Dollar', max_length=100, null=True)),
            ],
        ),
    ]
