# Generated by Django 4.1.1 on 2023-03-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'currencies'},
        ),
    ]
