# Generated by Django 4.1.1 on 2023-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_alter_currency_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar'), ('£', 'Pounds'), ('€', 'Euro'), ('₩', 'Korean Won'), ('₹', 'Indian Rupees'), ('¥', 'Chinese Yuan')], default='Dollar', max_length=100, null=True),
        ),
    ]
