# Generated by Django 4.1.1 on 2023-03-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_alter_currency_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar'), ('£', 'Pounds'), ('€', 'Euro'), ('₩', 'Korean Won'), ('₹', 'Indian Rupees'), ('¥', 'Chinese Yuan')], default='Dollar', max_length=100, null=True),
        ),
    ]
