# Generated by Django 4.1.1 on 2023-11-25 10:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0030_alter_payment_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_abbr', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
            options={
                'ordering': ['bank_fullname'],
            },
        ),
    ]
