# Generated by Django 4.1.1 on 2023-11-25 14:16

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0031_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='E.g. Master Card', max_length=200, null=True)),
                ('company_logo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(help_text='Card number should be 16 digits', max_length=16, unique=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField(help_text='CVV should be 3 digits', max_length=3)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.account')),
                ('card_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.cardtype')),
            ],
        ),
    ]
