# Generated by Django 4.1.1 on 2023-11-25 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0032_cardtype_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.PositiveIntegerField(help_text='Card number should be 16 digits', unique=True, validators=[django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.PositiveIntegerField(help_text='CVV should be 3 digits', validators=[django.core.validators.MaxValueValidator(999)]),
        ),
    ]
