# Generated by Django 4.1.1 on 2023-11-25 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0033_alter_card_card_number_alter_card_cvv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(help_text='Card number should be 16 digits', max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,16}$')]),
        ),
    ]
