# Generated by Django 4.1.1 on 2023-12-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0038_alter_account_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acct_id',
            field=models.IntegerField(auto_created=True, null=True, unique=True),
        ),
    ]
