# Generated by Django 4.1.1 on 2023-12-05 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0039_account_acct_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='account',
            name='acct_id',
        ),
    ]
